nginx:
  build: ./nginx
  links:
    - server-john
    - server-paul
    - server-george
    - server-ringo
  ports:
   - "3000:80"

server-john:
  build: ./src
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=John

server-paul:
  build: ./src
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=Paul

server-george:
  build: ./src
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=George

server-ringo:
  build: ./src
  links:
    - redis
  expose:
    - "3000"
  environment:
    - NAME=Ringo

redis:
  image: redis:alpine
  expose:
    - "6379"
  ports:
    - 6379:6379
